project_id = "keadkwromhlyvoyxvcmi"

[functions.openai-conversation]
verify_jwt = false

[functions.voice-to-autobiography]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.conversation-context-builder]
verify_jwt = false

[functions.ai-conversation-realtime]
verify_jwt = false

[functions.profile-extractor]
verify_jwt = false

[functions.realtime-token]
verify_jwt = false