project_id = "keadkwromhlyvoyxvcmi"

[functions.openai-conversation]
verify_jwt = true

[functions.voice-to-autobiography]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.conversation-context-builder]
verify_jwt = false

[functions.ai-conversation-realtime]
verify_jwt = false

[functions.profile-extractor]
verify_jwt = true

[functions.realtime-token]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.generate-chapter]
verify_jwt = true

[functions.generate-summary]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.test-conversation]
verify_jwt = false

[functions.simple-ai-chat]
verify_jwt = false