-- Drop old extracted columns from book_profiles table
-- Keeping only the new question-based structure
ALTER TABLE public.book_profiles 
  DROP COLUMN IF EXISTS full_name,
  DROP COLUMN IF EXISTS birthplace,
  DROP COLUMN IF EXISTS current_location,
  DROP COLUMN IF EXISTS birth_date,
  DROP COLUMN IF EXISTS birth_year,
  DROP COLUMN IF EXISTS occupation,
  DROP COLUMN IF EXISTS education,
  DROP COLUMN IF EXISTS career_highlights,
  DROP COLUMN IF EXISTS first_job,
  DROP COLUMN IF EXISTS family_background,
  DROP COLUMN IF EXISTS relationships_family,
  DROP COLUMN IF EXISTS marital_status,
  DROP COLUMN IF EXISTS siblings_count,
  DROP COLUMN IF EXISTS children_count,
  DROP COLUMN IF EXISTS parents_occupations,
  DROP COLUMN IF EXISTS nicknames,
  DROP COLUMN IF EXISTS personality_traits,
  DROP COLUMN IF EXISTS values_beliefs,
  DROP COLUMN IF EXISTS life_philosophy,
  DROP COLUMN IF EXISTS key_life_events,
  DROP COLUMN IF EXISTS life_themes,
  DROP COLUMN IF EXISTS cultural_background,
  DROP COLUMN IF EXISTS languages_spoken,
  DROP COLUMN IF EXISTS hobbies_interests,
  DROP COLUMN IF EXISTS challenges_overcome,
  DROP COLUMN IF EXISTS memorable_quotes;